In [2]:
np.arange(3)

NameError: name 'np' is not defined

In [3]:
from numpy import *

In [4]:
arange(3)

array([0, 1, 2])

In [5]:
zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [10]:
zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
ones(3)

array([1., 1., 1.])

In [8]:
ones(4,dtype=int)

array([1, 1, 1, 1])

In [12]:
ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
ones((5,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined