# Numpy 

In [1]:
import numpy as np # importing the numpy library and assigning it as a variable

In [2]:
np.__version__ # checking the version of the numpy

'1.26.4'

## Creating Arrays

In [3]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [5]:
arr = np.array(my_list)
arr

array([1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

## Arange function

In [7]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [8]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [11]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
np.arange(3.0,9.0)

array([3., 4., 5., 6., 7., 8.])

In [13]:
np.arange(10,2)   # first argument should always be less than second

array([], dtype=int32)

In [14]:
np.arange(-5,10)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [15]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [16]:
np.arange(-5,-10)  # first argument should always be less than second

array([], dtype=int32)

In [17]:
np.arange(5,5) # both argument values are equal so empty array

array([], dtype=int32)

In [18]:
np.arange(10,30,5)  # starting from 10 to 30 5 - step count

array([10, 15, 20, 25])

In [19]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [20]:
np.arange(5,150,5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130,
       135, 140, 145])

In [21]:
np.arange(5,150,5,4) # can pass only 3 arguments

TypeError: Cannot interpret '4' as a data type

## Zeros function

In [22]:
a = np.zeros(5) #parameter tunning : means by default ("zeros()" by default gives float values)
a

array([0., 0., 0., 0., 0.])

In [23]:
a = np.zeros(5,dtype=int) # hyperparameter tunning : means changing it from default (here changing the value to int type)
a

array([0, 0, 0, 0, 0])

In [24]:
b = np.zeros((5,5)) # matrix 5 X 5
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.zeros((5,5),dtype=int) # matrix 5 X 5

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
np.zeros((3,4)) # matrix 3 X 4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.zeros((5,4)) # matrix 5 X 4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.zeros((1,6))  # matrix 1 X 6

array([[0., 0., 0., 0., 0., 0.]])

In [29]:
np.zeros((10,30))  # matrix 10 X 30

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [30]:
n = (5,7)
n1 = (6,8)

In [31]:
print(np.zeros(n)) # parameter tunning

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [32]:
print(np.zeros(n1,dtype=int)) ## hyperparameter tunning 

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


## Ones function

In [33]:
np.ones(5) 

array([1., 1., 1., 1., 1.])

In [34]:
np.ones(5,dtype=int) # hyperparameter tunning : means changing it from default (here changing the value to int type)

array([1, 1, 1, 1, 1])

In [35]:
np.ones((5,5)) # matrix 5 X 5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
np.ones((5,5),dtype=int) # matrix 5 X 5

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
np.ones((3,4)) # matrix 3 X 4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
np.ones((5,4)) # matrix 5 X 4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
np.ones((1,6))  # matrix 1 X 6

array([[1., 1., 1., 1., 1., 1.]])

In [40]:
np.ones((10,30))  # matrix 10 X 30

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1

In [41]:
n = (5,7)
n1 = (6,8)

In [42]:
print(np.ones(n)) # parameter tunning

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [43]:
print(np.ones(n1,dtype=int)) ## hyperparameter tunning 

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [44]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [45]:
np.three((2,3))

AttributeError: module 'numpy' has no attribute 'three'

## Random function

In [46]:
np.random.rand(4) # return random number of length 4

array([0.41142751, 0.00294178, 0.66589556, 0.41487107])

In [47]:
np.random.randint(2,20) # return a random number between 2 to 20 excluding 20

4

In [48]:
np.random.randint(0,2)

1

In [49]:
np.random.randint(1,20,4) # return a random number between 10 to (20-1) of length 4 . 2nd argument shold always be excluded .

array([17, 11, 18, 11])

In [50]:
np.random.randint(30,20,10)  # 1st argument < 2nd argument

ValueError: low >= high

In [51]:
np.random.randint(20,30,10) 

array([21, 27, 25, 25, 26, 21, 29, 25, 21, 26])

In [52]:
np.random.randint(1)  

0

In [53]:
b = np.random.randint(10,35,(3,4)) #generate the element between 10-35 with 3 X 4 matrix
b

array([[14, 31, 16, 34],
       [31, 32, 19, 20],
       [28, 22, 14, 28]])

In [54]:
b[:]

array([[14, 31, 16, 34],
       [31, 32, 19, 20],
       [28, 22, 14, 28]])

In [55]:
b[0:2]        # return 0th rows to (2-1)rows

array([[14, 31, 16, 34],
       [31, 32, 19, 20]])

In [56]:
b[0,2] # return element of 0th row and 2 column

16

In [57]:
b[0:-1]

array([[14, 31, 16, 34],
       [31, 32, 19, 20]])

In [58]:
b[0,-1]

34

## Slicing

In [59]:
arr1 = list(range(5))
arr1

[0, 1, 2, 3, 4]

In [60]:
arr1[:]

[0, 1, 2, 3, 4]

In [61]:
arr1[2:]

[2, 3, 4]

In [62]:
arr1[:4]

[0, 1, 2, 3]

In [63]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[95,  0,  2, 13,  9, 29, 24, 30, 14, 18],
       [33, 97, 85,  2, 88, 86, 95, 80, 93, 17],
       [63, 69, 49,  9, 86, 27, 52, 47, 32, 97],
       [95, 90, 65, 62,  7, 14,  9,  0, 51,  1],
       [15, 29, 22, 15, 53, 35, 99, 30, 70,  9],
       [ 8, 38, 54, 93, 75, 62,  4, 90, 18, 48],
       [44, 74, 24, 64, 79, 24, 31, 59, 51, 34],
       [79, 93, 84, 37,  3, 72, 26, 58, 48, 68],
       [94, 15, 70, 61, 74, 57, 29, 39, 10, 63],
       [91, 50, 67, 85, 76, 68, 51, 27, 60, 64]])

In [64]:
arr2[0:6]

array([[95,  0,  2, 13,  9, 29, 24, 30, 14, 18],
       [33, 97, 85,  2, 88, 86, 95, 80, 93, 17],
       [63, 69, 49,  9, 86, 27, 52, 47, 32, 97],
       [95, 90, 65, 62,  7, 14,  9,  0, 51,  1],
       [15, 29, 22, 15, 53, 35, 99, 30, 70,  9],
       [ 8, 38, 54, 93, 75, 62,  4, 90, 18, 48]])

In [65]:
arr2[3:8]

array([[95, 90, 65, 62,  7, 14,  9,  0, 51,  1],
       [15, 29, 22, 15, 53, 35, 99, 30, 70,  9],
       [ 8, 38, 54, 93, 75, 62,  4, 90, 18, 48],
       [44, 74, 24, 64, 79, 24, 31, 59, 51, 34],
       [79, 93, 84, 37,  3, 72, 26, 58, 48, 68]])

In [66]:
arr2[-2:]

array([[94, 15, 70, 61, 74, 57, 29, 39, 10, 63],
       [91, 50, 67, 85, 76, 68, 51, 27, 60, 64]])

In [67]:
arr2[:-3]

array([[95,  0,  2, 13,  9, 29, 24, 30, 14, 18],
       [33, 97, 85,  2, 88, 86, 95, 80, 93, 17],
       [63, 69, 49,  9, 86, 27, 52, 47, 32, 97],
       [95, 90, 65, 62,  7, 14,  9,  0, 51,  1],
       [15, 29, 22, 15, 53, 35, 99, 30, 70,  9],
       [ 8, 38, 54, 93, 75, 62,  4, 90, 18, 48],
       [44, 74, 24, 64, 79, 24, 31, 59, 51, 34]])

In [68]:
arr2[-2:-7] # 1st argument < 2nd argument

array([], shape=(0, 10), dtype=int32)

In [69]:
arr2[-7:-7] # 1st argument < 2nd argument

array([], shape=(0, 10), dtype=int32)

In [70]:
arr2[-7:-2]

array([[95, 90, 65, 62,  7, 14,  9,  0, 51,  1],
       [15, 29, 22, 15, 53, 35, 99, 30, 70,  9],
       [ 8, 38, 54, 93, 75, 62,  4, 90, 18, 48],
       [44, 74, 24, 64, 79, 24, 31, 59, 51, 34],
       [79, 93, 84, 37,  3, 72, 26, 58, 48, 68]])

In [71]:
arr2[::-1] # reverse

array([[91, 50, 67, 85, 76, 68, 51, 27, 60, 64],
       [94, 15, 70, 61, 74, 57, 29, 39, 10, 63],
       [79, 93, 84, 37,  3, 72, 26, 58, 48, 68],
       [44, 74, 24, 64, 79, 24, 31, 59, 51, 34],
       [ 8, 38, 54, 93, 75, 62,  4, 90, 18, 48],
       [15, 29, 22, 15, 53, 35, 99, 30, 70,  9],
       [95, 90, 65, 62,  7, 14,  9,  0, 51,  1],
       [63, 69, 49,  9, 86, 27, 52, 47, 32, 97],
       [33, 97, 85,  2, 88, 86, 95, 80, 93, 17],
       [95,  0,  2, 13,  9, 29, 24, 30, 14, 18]])

In [72]:
arr2[::-3]

array([[91, 50, 67, 85, 76, 68, 51, 27, 60, 64],
       [44, 74, 24, 64, 79, 24, 31, 59, 51, 34],
       [95, 90, 65, 62,  7, 14,  9,  0, 51,  1],
       [95,  0,  2, 13,  9, 29, 24, 30, 14, 18]])

## Operations

In [73]:
arr

array([1, 2, 3, 4, 5])

In [74]:
arr.max()

5

In [75]:
arr.min()

1

In [76]:
arr.mean()

3.0

In [77]:
arr.sum()

15

## Reshape function

In [78]:
a1 = [1,2,3,4,5,6]
arr1 = np.array(a1)
arr1

array([1, 2, 3, 4, 5, 6])

In [79]:
arr1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [81]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [82]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [83]:
arr1.reshape(1,5) # because arr1 can be in the form of matrix which gives 6 as values  

ValueError: cannot reshape array of size 6 into shape (1,5)

In [84]:
arr1.reshape(3,2,order='C')

array([[1, 2],
       [3, 4],
       [5, 6]])

In [85]:
arr1.reshape(3,2,order='F')

array([[1, 4],
       [2, 5],
       [3, 6]])

In [86]:
arr1.reshape(3,2,order='A') 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [87]:
arr.reshape(3,2,order='K') 

ValueError: order 'K' is not permitted for reshaping

In [88]:
arr1.reshape(1,4)  

ValueError: cannot reshape array of size 6 into shape (1,4)

## Indexing

In [89]:
mat = np.arange(0,100).reshape(10,10) 
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [90]:
mat1 = np.arange(0,40).reshape(5,8) 
mat1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [91]:
mat1 = np.arange(0,40).reshape(8,5)  
mat1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [92]:
mat1 = np.arange(0,40).reshape(4,10)  
mat1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [93]:
mat1 = np.arange(0,40).reshape(10,4)  
mat1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [101]:
rows = 6
column = 8

In [102]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [103]:
mat[rows , column]

68

In [104]:
mat[:] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [105]:
mat[:column] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [106]:
# With Slices
mat[:,column] 

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [107]:
mat[rows:] 

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [108]:
mat[rows,:] 

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [109]:
mat[:rows] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [110]:
mat[rows:] 

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [111]:
mat[:column] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [112]:
mat[column:] 

array([[80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [113]:
mat[2,:] # return elements of 2nd row

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [114]:
mat[:,2] # return elements of 2nd column

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [115]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [116]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [117]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [118]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [119]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [120]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [121]:
mat[2:6,2:4] # 2:6 return from 2nd row to (6-1)th row /// 2:4 return from 2nd column to (4-1)th column

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [122]:
mat[1:2,2:4]  # 1:2 return from 1st row to (2-1) row /// 2:4 return from 2nd column to (4-1)th column

array([[12, 13]])

In [123]:
mat[3:5,0:8,]  # 3:5 return from 3rd row to (5-1) row /// 1:8 return from 0th column to (8-1)th column

array([[30, 31, 32, 33, 34, 35, 36, 37],
       [40, 41, 42, 43, 44, 45, 46, 47]])

## Masking

In [124]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [125]:
id(mat)

2626096108464

In [126]:
mat < 25

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [127]:
mat < 70

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [128]:
mat > 25

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [129]:
mat > 70

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [130]:
mat == 25

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [131]:
mat == 70

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [132]:
mat[mat==70]

array([70])

In [133]:
a2 = mat[mat<70] 
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69])

In [134]:
a6 = mat[mat<=70] 
a6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70])

In [135]:
a3 = mat[mat>70] 
a3

array([71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
       88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [136]:
a5 = mat[mat>=70] 
a5

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [137]:
a4 = mat[mat==70]
a4

array([70])